### ISSUE TITLE
Package not installable from sdist

### ISSUE THREAD

**Issue by xhochy** [chmp/ipytest#36]
Some files are missing, see

```
Non-user install because user site-packages disabled
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /private/tmp/pip-ephem-wheel-cache-ug7br3yw
Created temporary directory: /private/tmp/pip-req-tracker-oehxwbil
Initialized build tracking at /private/tmp/pip-req-tracker-oehxwbil
Created build tracker: /private/tmp/pip-req-tracker-oehxwbil
Entered build tracker: /private/tmp/pip-req-tracker-oehxwbil
Created temporary directory: /private/tmp/pip-install-ipqf4c2a
Processing $SRC_DIR
  Created temporary directory: /private/tmp/pip-req-build-cj348h0a
  Added file://$SRC_DIR to build tracker '/private/tmp/pip-req-tracker-oehxwbil'
    Running setup.py (path:/private/tmp/pip-req-build-cj348h0a/setup.py) egg_info for package from file://$SRC_DIR
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-cj348h0a/setup.py", line 10, in <module>
        long_description=pathlib.Path("Readme.md").read_text(),
      File "/Users/uwe/miniconda3/conda-bld/ipytest_1586412715596/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/pathlib.py", line 1227, in read_text
        with self.open(mode='r', encoding=encoding, errors=errors) as f:
      File "/Users/uwe/miniconda3/conda-bld/ipytest_1586412715596/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/pathlib.py", line 1213, in open
        return io.open(self, mode, buffering, encoding, errors, newline,
      File "/Users/uwe/miniconda3/conda-bld/ipytest_1586412715596/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/pathlib.py", line 1069, in _opener
        return self._accessor.open(self, flags, mode)
    FileNotFoundError: [Errno 2] No such file or directory: 'Readme.md'
Cleaning up...
  Removing source in /private/tmp/pip-req-build-cj348h0a
```

**Comment by chmp** [comment]
I guess this issue is fixed? Saw that now 0.8.1 is available on conda-forge. Thanks for the help :)
